### ISSUE TITLE
url.URL is not a constructor

### ISSUE THREAD

**Issue by GeorgesDick** [apache/cordova-browser#82] opened 2019-08-31 20:40 UTC
# Bug Report

## Problem
When trying to run (cordova run browser), got an error message "url.URL is not a constructor"

### What is expected to happen?
cordova run browser is supposed to run the app in a browser window

### What does actually happen?
Error message "url.URL is not a constructor"

## Information

Found a work around:
in file platforms/browser/cordova/lib/run.js change line 56 (or 57) form:
var projectUrl = (new url.URL(`http://localhost:${server.port}/${startPage}`)).href;
to
var projectUrl = `http://localhost:${server.port}/${startPage}`;

### Environment, Platform, Device

Windows 10

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by aderowbotham** [comment] 2020-06-08 15:56
I immediately ran into this problem on macOS following the Cordova [Getting Started Fast](https://cordova.apache.org/#getstarted) example with a fresh install.

**Comment by breautek** [comment] 2020-11-29 03:20
`URL` class was added in Node in version 6.13.0 & 7.0.0. Without the version information filled out I can't say for sure, but educated guess tells me you may have been running an unsupported version of node.

I've confirmed the "Getting Started Fast" works.

Since nowadays the minimum supported Node version is Node 10, I'll be closing this ticket.

**Closed by breautek** 2020-11-29 03:20 UTC
